### ISSUE TITLE
TODO: Add Installation and Usage Instructions to the README.md

### ISSUE THREAD

**Issue by twilson63** [ahodges13/Conway-s-Game-of-Life#1]
When shipping applications even for review, we want to set the stage up for success, often this is as simple as taking the time to craft the full readme up front:

Add Developer Install Instructions, Requirements, and a description on how to use the application.

For Example:
## Installation

```
git clone ....
cd ....
npm install
```
## Requirements
- NodeJS
- Grunt CLI `npm i grunt-cli -g`
## Usage

```
cd project
grunt serve
```

---

Following the current readme, I just get

```
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
```

---

You may also want to provide information on support and contributions

**Comment by ahodges13** [comment]
Great point!  I've updated the readme accordingly.  I also found a small bug as well, Flexbox Grid had not been added as a bower dependency.

**Comment by twilson63** [comment]
Looks Great!
