### ISSUE TITLE
TODO: Abstract the game logic from the presentation layer

### ISSUE THREAD

**Issue by twilson63** [ahodges13/Conway-s-Game-of-Life#2]
In the main controller you have all of your game rules and logic, abstract that from the controller and put the rules in a separate service or factory, or even just a plain javascript object. 

In the controller make your code as simple as possible, only manage ui transitions.

New Game -> var g = gol.createGame()
Play Game -> $scope.data = g.play()
Stop Game -> ...

Make sense? Let me know if you want to discuss.  The angular controller, should not know anything about the game of life except its api endpoints:
- createGame (constructor)
- play (function)
- stop (function)
- board (property array)

Then the controller template binds and renders based on the game array as it is changed

**Comment by ahodges13** [comment]
Great point!  My second to last position was much better about segregating out layers like this.  I've checked in a new logic service, take a look and see if it's more along the lines of what you would like to see.

The only question I had, was the toggle method.  Would you keep that in the controller?  Or move it back to the service layer?

**Comment by twilson63** [comment]
I hate answering questions with other questions, but I would think of it like this, lets say all of the sudden the boss contacts you and says, hey this is great and we want to ship this game with several different presentation layers, and we have several teams coming your way to create the front ends. I would want my api to describe as much as possible the desired functionality, so in that case, I would not expose the actual data structures, but provide an abstraction that makes it pretty explicit how to interact with the game.  Then I could implement in several different presentation engines without having side effects.  For Example, what if during the toggle, a new developer passed a string or object in to the cell, or what if they changes grid[0] = null during the toggle, whereas game.cell(0,1).toggle() is much more manageable and explicit.  It also provides you with the capability to change the internals without having to change the externals.

Make sense?

**Comment by twilson63** [comment]
While returning a nested array to paint the presentation layer, but it is always a copy of the state not the actual state, so if a presentation team tried to make adjustments it would just go into vapor, the grid would always be returned as a readonly clone.

**Comment by twilson63** [comment]
Looking good!
