### ISSUE TITLE
REFACTOR: Underscore.js - start game function

### ISSUE THREAD

**Issue by twilson63** [ahodges13/Conway-s-Game-of-Life#3]
Have you ever used underscore.js

Take a look at the _.times function and see if you can use it to refactor the start game code and remove the for loops.  For loops in javascript can make scoping hard, by using iterators you create closures and control the local scope much easier.

take a look at 

`http://underscorejs.org/#times`

and try to re-implement the start game function with no for loops.

**Comment by ahodges13** [comment]
Underscore looks really cool - I have never dived down into all of the available capabilities, nor understood why they were better to use (scope control, etc).  Thanks for the suggestion!  I pushed in a change set that refactored the start game function, let me know if that's what you were imagining.

**Comment by twilson63** [comment]
Awesome!

one nice thing about the times function is that it automatically returns an array

So you don't have to instantiate the arrays and push values in:

You can for example:

``` js
_.times(20, function () {
  return []
})
```

This will return 20 items with a blank array as the value

You can also default the value false

``` js
_.times(20, function() { return false })
```

which will return 20 items with the value false
So lets apply this ability to your function

``` js
var setFalse = function() { return false }
var grid = _.times(20, function() { return _.times(20, setFalse) })
```

So really, you could have a method like the following:

``` js
this.startGame = function(height, width) {
  var setFalse = function () { return false }
  return _.times(height, function () { return _.times(width, setFalse) })
}
```

**Comment by ahodges13** [comment]
Awesome!!  This is really neat how you can do so much, with so few, concise statements.  And it's still readable, instead of being too complex to figure out what's really happening!  lol

I pushed in a change to comment out the attempt at continuous play, and refactored the startGame method, as you suggested above.

**Comment by ahodges13** [comment]
I believe this Refactor is complete.
