### ISSUE TITLE
REFACTOR: Underscore.js getNeighbors use functional patterns to reduce un-needed boilierplate

### ISSUE THREAD

**Issue by twilson63** [ahodges13/Conway-s-Game-of-Life#4]
In the get Neighbors function you have some redundant statements, try 

creating a constant array of neighbor locations

```
var TOP_LEFT = [-1, -1]
var TOP = [0, -1] 
etc

var NEIGHBORS = [TOP_LEFT, TOP, TOP_RIGHT, MIDDLE_LEFT, MIDDLE_RIGHT, BOTTOM_LEFT, BOTTOM, BOTTOM_RIGHT]
```

Then in the getNeighbors function use the _(NEIGHBORS).filter(...).length to return the count.  This should reduce some of the boilier plate and be easier to read.  Hopefully, give it a try and lets discuss.

**Comment by ahodges13** [comment]
Awesome!  That worked out really well.  Much cleaner code.  Check out the latest push I did to see the result.

**Comment by twilson63** [comment]
Very Nice!
