### ISSUE TITLE
REFACTOR: iterate function

### ISSUE THREAD

**Issue by twilson63** [ahodges13/Conway-s-Game-of-Life#5]
Lets take a look at the iterate function, there is a lot going there, thing of ways to simplify this method, maybe you can take a look at the underscore map function, maybe you can use a clone and a nested set of map functions to reduce the complexity of this function.  You might be able to use the _.filter method to reduce some conditional logic.

Try to refactor the function so that you are not using any for loops or if statements.

**Comment by ahodges13** [comment]
Sweet!  I did it using _.times and a tertiary statement.  Take a look, and let me know what you think?

**Comment by twilson63** [comment]
Awesome,

So there is a method called `map` in underscore that iterates through an array and returns a new array.

Since during an iteration you want to map through your columns and rows then determine whether each cell should live or die and generate a new grid.

try this map function the second argument of the iterator should be the position of the array the first argument is the value, then the map returns a new array without affecting the state/data of the old array as it iterates.

``` js
    this.iterate = function(currentGrid) {
      var self = this;
      return _(currentGrid).map(function (v, i) {
        return _(v).map(function (cell, k) {
          return cell ? self.willLive(currentGrid, i, k) : self.isBorn(currentGrid, i, k);
        });
      });
    };
```

**Comment by ahodges13** [comment]
Neat!  Ok, I did that.  Is there a benefit to using the map function in this instance, over the times?  That was really the only change there.

**Comment by twilson63** [comment]
Yes,

So the map function is a very common function if functional programming, you may have heard of terms like `map` and `reduce` - but basically the map function or mapObject can iterate over a collection or object and pass in the internal value at each position then return a new collection or object as a result.  

Make Sense?  The times function is valuable when you do not have a collection or object already built.

Thanks

Tom
