### ISSUE TITLE
FEATURE: continuous iteration until game is complete

### ISSUE THREAD

**Issue by twilson63** [ahodges13/Conway-s-Game-of-Life#6]
When the user clicks the play button, continuously loop through the steps until there are no more alive cells.

Try to implement this with no for loops or if statements.

**Comment by twilson63** [comment]
Instead of using a while loop, use a setTimeout and do 500 ms between each function call

``` js
function continuous() {
  if (done) return
  ....
  $scope.grid = ...
  setTimeout(continuous, 500)
}

continuous()
```

Let me know if this makes sense, happy to walk through it, but basically you should not need the while and angular should take care of the presentation

**Comment by ahodges13** [comment]
Ok, cool - I hadn't thought of doing a recursive approach.  So, I have the continuous play part working - it stops whenever no cells have changed after an iteration, i.e. no cell dies && no cell is born.  But - the timeout still isn't working.  As in, you see the first iteration and then the last iteration painted on the screen.  I can't seem to get it to paint each iteration in between, for some reason.  I've tried setTimeout, _.delay & $timeout - all have the same effect.  What am I missing?  See latested changeset.  Thanks!!

**Comment by ahodges13** [comment]
I believe this feature is complete.
